### ISSUE TITLE
minhv

### ISSUE THREAD

**Issue by dangerblue** [sifive/clic-spec#16]
when interrupt hardware vectoring, the minhv used to record the exception, also, the mepc will store the trap handler address according to the spec. In this case, the original mepc will be overwritten,  the software can not go back to the context that the interrupt happens.

**Comment by Kevin-Andes** [comment]
You have very good observation and indeed this is a problem.  In current spec., mepc and mcause will always be overwritten whenever an exception or NMI occur. Therefore, we are proposing a general solution to solve this problem fundamentally. 

Our basic idea is to have 2 CSRs to automatically backup (stack) mepc and mcause so that exceptions/NMI can always be recovered 100%. We will discuss more details in the meeting.

**Comment by kasanovic** [comment]
We decided that the separate NMI approach is actually orthogonal to the local interrupt controller, so the additional NMI support is now being proposed as extension of main privileged architecture. Closing here for this reason.
