### ISSUE TITLE
Configuration of interrupts from Supervisor and User mode

### ISSUE THREAD

**Issue by khannaudit** [sifive/clic-spec#20]
1. In CLINT mode, interrupts delegated to S mode would use the vector table stored at address `stvec.BASE`. However, in CLIC modes, there is no mention of supervisor/user mode equivalents of the new `mtvt` CSR. Do supervisor mode interrupts also use `mtvt` (a machine level CSR)?

2. From the memory map, the `cliccfg` register is only present in the Machine mode apertures. How would Supervisor and User mode code be able to correctly set levels, priorities, selective-vectoring and/or delegate interrupts without being able to determine the fields of `cliccfg`? Shouldn't there be a mention of setting up read-only permissions for this register from lower privilege modes?

**Comment by jim-wilson** [comment]
1) Note that the 'm' is in a slightly different font, because it is a variable.  This is mentioned at the top of section 3 in the table, and below it.

2) Cliccfg, and clicintcfg, are memory mapped I/O registers, not CSRs.  So maybe this is just a matter of getting the memory permissions right for these memory regions?
